# Generated by Django 4.2.6 on 2023-11-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts_pro', '0004_post_like_counts_post_unlike_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_counts',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlike_counts',
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='like', to='contenttypes.contenttype'),
        ),
    ]
